// Code generated by "genpacket -packet=ChatMessagePacket -output=chat_gen.go"; DO NOT EDIT.

package packet

import "io"

func (c *ChatMessagePacket) Write(w io.Writer) error {
	var err error
	if err = c.Message.Write(w); err != nil {
		return err
	}
	if err = c.Position.Write(w); err != nil {
		return err
	}
	return nil
}
func (c *ChatMessagePacket) Read(r io.Reader) error {
	var err error
	if err = c.Message.Read(r); err != nil {
		return err
	}
	if err = c.Position.Read(r); err != nil {
		return err
	}
	return nil
}
