// Code generated by "stringer -type=Direction -output direction_string.go -linecomment"; DO NOT EDIT.

package packet

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ClientBound-0]
	_ = x[ServerBound-1]
}

const _Direction_name = "client-boundserver-bound"

var _Direction_index = [...]uint8{0, 12, 24}

func (i Direction) String() string {
	if i >= Direction(len(_Direction_index)-1) {
		return "Direction(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Direction_name[_Direction_index[i]:_Direction_index[i+1]]
}
