// Code generated by "genpacket -packet=LoginSuccessPacket -output=login_success_gen.go"; DO NOT EDIT.

package packet

import "io"

func (l *LoginSuccessPacket) Write(w io.Writer) error {
	var err error
	if err = l.UUID.Write(w); err != nil {
		return err
	}
	if err = l.Username.Write(w); err != nil {
		return err
	}
	return nil
}
func (l *LoginSuccessPacket) Read(r io.Reader) error {
	var err error
	if err = l.UUID.Read(r); err != nil {
		return err
	}
	if err = l.Username.Read(r); err != nil {
		return err
	}
	return nil
}
