// Code generated by "genpacket -packet=PlayerPositionLookPacket -output=player_position_look_gen.go"; DO NOT EDIT.

package packet

import "io"

func (p *PlayerPositionLookPacket) Write(w io.Writer) error {
	var err error
	if err = p.X.Write(w); err != nil {
		return err
	}
	if err = p.Y.Write(w); err != nil {
		return err
	}
	if err = p.Z.Write(w); err != nil {
		return err
	}
	if err = p.Yaw.Write(w); err != nil {
		return err
	}
	if err = p.Pitch.Write(w); err != nil {
		return err
	}
	if err = p.Flags.Write(w); err != nil {
		return err
	}
	if err = p.TeleportID.Write(w); err != nil {
		return err
	}
	return nil
}
func (p *PlayerPositionLookPacket) Read(r io.Reader) error {
	var err error
	if err = p.X.Read(r); err != nil {
		return err
	}
	if err = p.Y.Read(r); err != nil {
		return err
	}
	if err = p.Z.Read(r); err != nil {
		return err
	}
	if err = p.Yaw.Read(r); err != nil {
		return err
	}
	if err = p.Pitch.Read(r); err != nil {
		return err
	}
	if err = p.Flags.Read(r); err != nil {
		return err
	}
	if err = p.TeleportID.Read(r); err != nil {
		return err
	}
	return nil
}
