// Code generated by "genpacket -packet=ServerQueryPacket -output=server_query_gen.go"; DO NOT EDIT.

package packet

import "io"

func (s *ServerQueryPacket) Write(w io.Writer) error {
	return nil
}
func (s *ServerQueryPacket) Read(r io.Reader) error {
	return nil
}
