// Code generated by "stringer -type=ConnectionState -output state_string.go -linecomment"; DO NOT EDIT.

package game

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[HandshakeState-0]
	_ = x[StatusState-1]
	_ = x[LoginState-2]
	_ = x[PlayState-3]
}

const _ConnectionState_name = "HandshakeStatusLoginPlay"

var _ConnectionState_index = [...]uint8{0, 9, 15, 20, 24}

func (i ConnectionState) String() string {
	if i >= ConnectionState(len(_ConnectionState_index)-1) {
		return "ConnectionState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ConnectionState_name[_ConnectionState_index[i]:_ConnectionState_index[i+1]]
}
