// Code generated by "stringer -type=Gamemode -output gamemode_string.go -linecomment"; DO NOT EDIT.

package mcproto

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Survival-0]
	_ = x[Creative-1]
	_ = x[Adventure-2]
	_ = x[Spectator-3]
}

const _Gamemode_name = "SurvivalCreativeAdventureSpectator"

var _Gamemode_index = [...]uint8{0, 8, 16, 25, 34}

func (i Gamemode) String() string {
	if i >= Gamemode(len(_Gamemode_index)-1) {
		return "Gamemode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Gamemode_name[_Gamemode_index[i]:_Gamemode_index[i+1]]
}
