// Code generated by "stringer -type=Hand -output hand_string.go -linecomment"; DO NOT EDIT.

package mcproto

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[HandLeft-0]
	_ = x[HandRight-1]
}

const _Hand_name = "LeftRight"

var _Hand_index = [...]uint8{0, 4, 9}

func (i Hand) String() string {
	if i < 0 || i >= Hand(len(_Hand_index)-1) {
		return "Hand(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Hand_name[_Hand_index[i]:_Hand_index[i+1]]
}
