// Code generated by "genpacket -packet=JoinGamePacket -output=join_game_gen.go"; DO NOT EDIT.

package mcproto

import "io"

func (j *JoinGamePacket) Write(w io.Writer) error {
	var err error
	if err = j.PlayerID.Write(w); err != nil {
		return err
	}
	if err = j.GameMode.Write(w); err != nil {
		return err
	}
	if err = j.Dimension.Write(w); err != nil {
		return err
	}
	if err = j.HashedSeed.Write(w); err != nil {
		return err
	}
	if err = j.MaxPlayers.Write(w); err != nil {
		return err
	}
	if err = j.LevelType.Write(w); err != nil {
		return err
	}
	if err = j.ViewDistance.Write(w); err != nil {
		return err
	}
	if err = j.ReducedDebug.Write(w); err != nil {
		return err
	}
	if err = j.EnableRespawnScreen.Write(w); err != nil {
		return err
	}
	return nil
}
func (j *JoinGamePacket) Read(r io.Reader) error {
	var err error
	if err = j.PlayerID.Read(r); err != nil {
		return err
	}
	if err = j.GameMode.Read(r); err != nil {
		return err
	}
	if err = j.Dimension.Read(r); err != nil {
		return err
	}
	if err = j.HashedSeed.Read(r); err != nil {
		return err
	}
	if err = j.MaxPlayers.Read(r); err != nil {
		return err
	}
	if err = j.LevelType.Read(r); err != nil {
		return err
	}
	if err = j.ViewDistance.Read(r); err != nil {
		return err
	}
	if err = j.ReducedDebug.Read(r); err != nil {
		return err
	}
	if err = j.EnableRespawnScreen.Read(r); err != nil {
		return err
	}
	return nil
}
