// Code generated by "genpacket -packet=PluginMessagePacket -output=plugin_message_gen.go"; DO NOT EDIT.

package mcproto

import "io"

func (p *PluginMessagePacket) Write(w io.Writer) error {
	var err error
	if err = p.Channel.Write(w); err != nil {
		return err
	}
	if err = p.Data.Write(w); err != nil {
		return err
	}
	return nil
}
func (p *PluginMessagePacket) Read(r io.Reader) error {
	var err error
	if err = p.Channel.Read(r); err != nil {
		return err
	}
	if err = p.Data.Read(r); err != nil {
		return err
	}
	return nil
}
