// Code generated by "stringer -type=PacketDirection -output direction_string.go -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ClientBound-0]
	_ = x[ServerBound-1]
}

const _PacketDirection_name = "client-boundserver-bound"

var _PacketDirection_index = [...]uint8{0, 12, 24}

func (i PacketDirection) String() string {
	if i >= PacketDirection(len(_PacketDirection_index)-1) {
		return "PacketDirection(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PacketDirection_name[_PacketDirection_index[i]:_PacketDirection_index[i+1]]
}
