// Code generated by "stringer -type=Side -output side_string.go -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ClientSide-0]
	_ = x[ServerSide-1]
}

const _Side_name = "ClientServer"

var _Side_index = [...]uint8{0, 6, 12}

func (i Side) String() string {
	if i >= Side(len(_Side_index)-1) {
		return "Side(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Side_name[_Side_index[i]:_Side_index[i+1]]
}
