// Code generated by "genpacket -packet=BrandChannel -output=brand_gen.go"; DO NOT EDIT.

package channel

import "io"

func (b *BrandChannel) Write(w io.Writer) error {
	var err error
	if err = b.Brand.Write(w); err != nil {
		return err
	}
	return nil
}
func (b *BrandChannel) Read(r io.Reader) error {
	var err error
	if err = b.Brand.Read(r); err != nil {
		return err
	}
	return nil
}
